menu:
    Home: /
    Archive: /archives/
    About: /post/about.html
    GitHub: https://github.com/jiandansousuo/jiandansousuo.com
    Rss: /atom.xml

favicon: /favicon.ico
logo: /img/logo.jpg

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
ga: false

# Copyright Infomation
startyear: 2017
