menu:
    Home: /
    Archive: /archives/
    GitHub: https://github.com/jiandansousuo/jiandansousuo.com
    Rss: /atom.xml

favicon: /favicon.ico
logo: /img/logo.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
ga: false

# Copyright Infomation
startyear: 2017
